#!/usr/bin/env bash
# Install the passwordless-sudo entry the in-app "Shutdown Jetson" /
# "Reboot Jetson" buttons (and the companion-app reboot endpoint) need.
#
# Why this script exists:
#
#   The Sirena UI buttons call `nina.jetson_net.host_control.queue_*()`,
#   which fires `sudo -n /usr/bin/systemctl poweroff` (or `reboot`).
#   `sudo -n` means "no password prompt" - it returns immediately
#   with "operation not permitted" unless we've previously declared a
#   NOPASSWD rule for this exact command + user. So out of the box,
#   pressing Shutdown / Reboot in the GUI does nothing visible (it
#   just logs the rejection). This script writes the rule.
#
# What it does (idempotent - safe to re-run):
#
#   1. Picks the kiosk user. By default the user running the script
#      (or $SUDO_USER if invoked via `sudo`); override with the
#      first positional argument.
#   2. Drops `/etc/sudoers.d/nina-host-power` with the exact argv
#      list `host_control.py` tries, in order.
#   3. Runs `visudo -cf` on the new file BEFORE moving it into place
#      so a typo can never wedge sudo (the file is written to a temp
#      path, validated, then mv'd).
#   4. Smoke-tests `sudo -n /usr/bin/systemctl --version` as the
#      kiosk user to confirm the rule took effect.
#
# Usage:
#
#   sudo bash scripts/install-nina-host-power.sh           # auto-detect user
#   sudo bash scripts/install-nina-host-power.sh nina      # explicit user
#
# Uninstall:
#
#   sudo rm /etc/sudoers.d/nina-host-power
#
# Security note: this rule is narrow on purpose. It grants ONLY the
# specific binaries needed to power off / reboot the box - no shell,
# no editor, no broad systemctl. An attacker who gets the kiosk user
# can already shut the robot down via the OSK / GUI, so this rule
# adds no real privilege beyond what the panel exposes.

set -euo pipefail

log()  { printf "\033[1;34m[host-power]\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m[host-power]\033[0m %s\n" "$*" >&2; }
die()  { printf "\033[1;31m[host-power]\033[0m %s\n" "$*" >&2; exit 1; }

# --------------------------------------------------------------------
# 1) Resolve target user
# --------------------------------------------------------------------

if [[ $EUID -ne 0 ]]; then
    die "must run as root (sudo bash $0)"
fi

TARGET_USER="${1:-${SUDO_USER:-}}"
if [[ -z "${TARGET_USER}" ]]; then
    die "could not determine kiosk user.
Pass it explicitly:
    sudo bash $0 <kiosk-username>
(e.g. 'nina', or whatever \`id -un\` prints in the GUI session)"
fi

if ! id -u "${TARGET_USER}" >/dev/null 2>&1; then
    die "user '${TARGET_USER}' does not exist on this system."
fi

log "Granting passwordless poweroff/reboot to user '${TARGET_USER}'"

# --------------------------------------------------------------------
# 2) Compose the sudoers fragment
# --------------------------------------------------------------------
#
# The argv list MUST stay in sync with
# nina/jetson_net/host_control.py:_POWEROFF_CANDIDATES and
# _REBOOT_CANDIDATES. If you add a new candidate there, add it here.
# Mismatched paths will *silently fall back* to the next candidate at
# runtime, so the GUI keeps working - but it's wasteful, so keep
# them aligned.

TMP_FILE="$(mktemp)"
trap 'rm -f "${TMP_FILE}"' EXIT

cat > "${TMP_FILE}" <<EOF
# Generated by scripts/install-nina-host-power.sh
#
# Grants the Sirena Nina kiosk user the ability to poweroff / reboot
# the Jetson without a password, so the in-app "Shutdown Jetson" and
# "Reboot Jetson" buttons (and the companion-app /v1/system/* HTTP
# endpoints) work. Mirrors host_control.py's candidate argvs.

${TARGET_USER} ALL=(root) NOPASSWD: \\
    /usr/bin/systemctl poweroff, \\
    /usr/bin/systemctl reboot, \\
    /bin/systemctl poweroff, \\
    /bin/systemctl reboot, \\
    /sbin/poweroff, \\
    /usr/sbin/poweroff, \\
    /sbin/reboot, \\
    /usr/sbin/reboot, \\
    /sbin/shutdown -h now, \\
    /sbin/shutdown -r now
EOF

# --------------------------------------------------------------------
# 3) Validate with visudo -cf, then install atomically
# --------------------------------------------------------------------

if ! visudo -cf "${TMP_FILE}" >/dev/null 2>&1; then
    # Re-run without redirection so the operator sees the parse error.
    visudo -cf "${TMP_FILE}" || true
    die "visudo rejected the generated file - aborting before touching sudo.
This is a bug in the installer; please report it. Sudo on this box is
unchanged."
fi

DEST="/etc/sudoers.d/nina-host-power"
install -m 0440 -o root -g root "${TMP_FILE}" "${DEST}"
log "wrote ${DEST} (mode 0440, owner root:root)"

# --------------------------------------------------------------------
# 4) Smoke-test the rule
# --------------------------------------------------------------------
#
# `--version` is a side-effect-free probe: if sudo would have prompted
# (rule didn't take), -n makes it return non-zero immediately and we
# surface a clear error. We pick the FIRST candidate path that exists
# on this system so the check matches reality.

SYSTEMCTL_BIN=""
for c in /usr/bin/systemctl /bin/systemctl; do
    [[ -x "$c" ]] && { SYSTEMCTL_BIN="$c"; break; }
done

if [[ -n "${SYSTEMCTL_BIN}" ]]; then
    # We probe with the real argvs we'll run at GUI-button time
    # (`systemctl poweroff` / `reboot`) and add --dry-run so the
    # smoke test doesn't actually power the box off if NOPASSWD took
    # effect. --dry-run was added in systemd v247 (Ubuntu 22.04
    # ships v249) so this works on JetPack 5/6 images; older systemd
    # boxes will fail the dry-run with rc=1 but the GUI buttons will
    # still work at runtime.
    if su -s /bin/bash - "${TARGET_USER}" -c \
         "sudo -n ${SYSTEMCTL_BIN} poweroff --dry-run >/dev/null 2>&1" ; then
        log "smoke test passed: '${TARGET_USER}' can sudo -n ${SYSTEMCTL_BIN} poweroff (dry-run) without prompt"
    elif su -s /bin/bash - "${TARGET_USER}" -c \
         "sudo -n ${SYSTEMCTL_BIN} --version >/dev/null 2>&1" ; then
        log "smoke test passed: '${TARGET_USER}' can sudo -n ${SYSTEMCTL_BIN} without prompt"
        warn "(systemctl --dry-run rejected the dry-run - probably old systemd; GUI buttons will still work)"
    else
        warn "smoke test failed: 'sudo -n ${SYSTEMCTL_BIN}' still prompts.
This usually means an earlier /etc/sudoers entry is overriding NOPASSWD.
Check:
    sudo grep -RE 'requiretty|authenticate' /etc/sudoers /etc/sudoers.d/
The new rule is installed; you may just need to remove the conflicting
older entry, or pass an explicit username to this installer (the user
running the GUI may not be the same as the user who ran 'sudo bash')."
    fi
else
    warn "no systemctl binary found in /usr/bin or /bin; can't smoke-test.
The rule is installed; shutdown/reboot from the GUI will fall back to
/sbin/poweroff or /sbin/shutdown -h now at runtime."
fi

cat <<EOF

Sirena host-power passwordless sudo installed.

  rule file       : ${DEST}
  target user     : ${TARGET_USER}

Test from the kiosk session (it should NOT prompt and should NOT
actually power off because of --dry-run):

  sudo -n systemctl poweroff --dry-run

To remove:

  sudo rm ${DEST}

Once removed, the GUI's Shutdown / Reboot buttons will silently log
"operation not permitted" and do nothing, same as before installing.
EOF
